### ISSUE TITLE
Difference to jq

### ISSUE THREAD

**Issue by wildeyes** [ldn-softdev/jtc#15]
jq is pretty standard, how is this tool different / unique? what does it do better?

**Comment by ldn-softdev** [comment]
jq is pretty standard only because it was developed much earlier than `jtc`.  If they came up around the same time, who knows what would be the standard now.

The difference is outlined in the section [jtc vs jq](https://github.com/ldn-softdev/jtc#jtc-vs-jq). There are a few major diffs:

- `jtc` knowledge base to achieve most of JSON queries is much smaller and limited than jq's (one is a utility, another is a language) - that facilitates higher feasibility of queries with `jtc`
- `jtc` offers a unique approach for traversing JSON trees - no other utility offers traversing JSON tree upwards (only downwards) - that allows building natively invariant solutions (which won't break as long as relationship between walking elements is maintained, while other tree structures may vary)
- `jtc` has a much lower entry threshold for start building JSON queries and achieving solutions, as every operation/ incremental building step provides an immediate visual feedback and allows building query bit by bit (which is not always possible with orthodox approaches like jq's)  
- `jtc` is faster in majority of the cases (on similar queries)

the fact that `jtc` is a utility and not a language (unlike jq) one may view it as a disadvantage - `jtc` operates only within JSON field of operations while `jq` being fully blown DSL may implements even non-JSON program. However, idiomatic  (unix) approach is this: if there's a requirement to build something outside of field of operation, then GPL (e.g. Python) to be considered.

**Comment by wildeyes** [comment]
Very nice, thank you!

**Comment by ldn-softdev** [comment]
btw, you might be interested: with the latest update `jtc` becomes multi-threaded - it reads/parses multiple files concurrently (given multiple files and multi-core cpu). That's one more difference between jq and `jtc`.
